-- Task 3A: Join power plant data with energy production data
-- Joining intel.power_plants and intel.energy_by_plant tables on plant_code
SELECT *
FROM intel.power_plants AS pp
    JOIN intel.energy_by_plant AS ebp
    ON pp.plant_code = ebp.plant_code;

-- Task 3B: Calculate the total number of renewable energy power plants by region
-- Filtering only renewable energy plants and counting per region
WITH new_data1 AS (
    SELECT
        pp.region,
        ebp.energy_type
    FROM
        intel.power_plants AS pp
        JOIN intel.energy_by_plant AS ebp
        ON pp.plant_code = ebp.plant_code
)
SELECT
    region,
    COUNT(*) AS total_num_renewable_energy
FROM new_data1
WHERE
    energy_type = 'renewable_energy'
GROUP BY
    region
ORDER BY
    total_num_power_plants DESC;

-- Task 3C: Calculate the total number of Solar Photovoltaic plants and their total energy generated by region
-- Focus only on plants using 'Solar Photovoltaic' technology
WITH new_data2 AS (
    SELECT
        pp.region,
        pp.primary_technology,
        ebp.energy_type,
        pp.fuel_types,
        pp.plant_code,
        ebp.energy_generated_mw
    FROM
        intel.power_plants AS pp
        JOIN intel.energy_by_plant AS ebp
        ON pp.plant_code = ebp.plant_code
)
SELECT
    region,
    COUNT(*) AS total_num_power_plants,
    SUM(energy_generated_mw) AS total_energy_generated
FROM new_data2
WHERE
    primary_technology = 'Solar Photovoltaic'
GROUP BY
    region
ORDER BY
    total_num_power_plants DESC;

-- Task 3D: Filter regions that have at least 50 Solar Photovoltaic plants
-- This helps to analyze larger-scale solar regions
WITH new_data3 AS (
    SELECT
        pp.region,
        pp.primary_technology,
        ebp.energy_type,
        pp.fuel_types,
        pp.plant_code,
        ebp.energy_generated_mw
    FROM
        intel.power_plants AS pp
        JOIN intel.energy_by_plant AS ebp
        ON pp.plant_code = ebp.plant_code
)
SELECT
    region,
    COUNT(*) AS total_num_power_plants,
    SUM(energy_generated_mw) AS total_energy_generated
FROM new_data3
WHERE
    primary_technology = 'Solar Photovoltaic'
GROUP BY
    region
HAVING
    COUNT(*) >= 50
ORDER BY
    total_num_power_plants DESC