-- Task 4A: Calculate total renewable energy generated by region for each hour of the day
-- Extract the hour from time_at_end_of_hour and group energy generation by hour and region
SELECT
    region,
    DATE_PART('hour', time_at_end_of_hour) AS hour_of_day,
    SUM(hydropower_and_pumped_storage + wind + solar) AS total_renewable_energy_mw
FROM intel.energy_data
GROUP BY
    region,
    hour_of_day
ORDER BY hour_of_day;

-- Task 4B: Filter the hourly renewable energy generation to only 'California' and 'Northwest' regions
-- This allows comparison of renewable energy trends between the two regions
SELECT
    region,
    DATE_PART('hour', time_at_end_of_hour) AS hour_of_day,
    SUM(hydropower_and_pumped_storage + wind + solar) AS total_renewable_energy_mw
FROM intel.energy_data
WHERE 
    region = 'California'
    OR region = 'Northwest'
GROUP BY
    region,
    hour_of_day
ORDER BY region;